// @ts-nocheck
export const metadata = {
  title: 'Loopstudios',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
        <link rel="icon" href="../public/images/logo.svg" sizes="any" />
      </head>
      <body>{children}</body>
    </html>
  )
}
